name: Update latest tag

on:
  release:
    types: [published]

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Move latest tag to current commit
        run: |
          git tag -d latest || true
          git tag latest
          git push origin :refs/tags/latest
          git push origin --tags

      - name: Create a GitHub release for the latest tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
